### ISSUE TITLE
python3.9 runtime

### ISSUE THREAD

**Issue by untereiner** [scaleway/scaleway-functions-runtimes#7]
#### What problem would the feature you're requesting solve? Please describe.
I would have a more recent python runtime (i.e. 3.9)

#### Describe the solution you'd like
An runtime image tagged python 3.9

#### Describe alternatives you've considered
There is none. My code needs 3.9 features

#### Additional context
n.a.

**Comment by thomas-tacquet** [comment]
Thank you for raising an issue, Python 3.9 has been added to available runtimes :)
